/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as ConsoleRouteImport } from './routes/console'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MenuCategoryIdRouteImport } from './routes/menu/$categoryId'
import { Route as ConsolePedidosRouteImport } from './routes/console/pedidos'
import { Route as ConsoleFinancaRouteImport } from './routes/console/financa'
import { Route as ConsoleDashboardRouteImport } from './routes/console/dashboard'
import { Route as ConsoleDashboardDelRouteImport } from './routes/console/dashboard/del'
import { Route as ConsoleDashboardAddRouteImport } from './routes/console/dashboard/add'

const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRoute = ConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuCategoryIdRoute = MenuCategoryIdRouteImport.update({
  id: '/$categoryId',
  path: '/$categoryId',
  getParentRoute: () => MenuRoute,
} as any)
const ConsolePedidosRoute = ConsolePedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleFinancaRoute = ConsoleFinancaRouteImport.update({
  id: '/financa',
  path: '/financa',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleDashboardRoute = ConsoleDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleDashboardDelRoute = ConsoleDashboardDelRouteImport.update({
  id: '/del',
  path: '/del',
  getParentRoute: () => ConsoleDashboardRoute,
} as any)
const ConsoleDashboardAddRoute = ConsoleDashboardAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => ConsoleDashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/console': typeof ConsoleRouteWithChildren
  '/menu': typeof MenuRouteWithChildren
  '/console/dashboard': typeof ConsoleDashboardRouteWithChildren
  '/console/financa': typeof ConsoleFinancaRoute
  '/console/pedidos': typeof ConsolePedidosRoute
  '/menu/$categoryId': typeof MenuCategoryIdRoute
  '/console/dashboard/add': typeof ConsoleDashboardAddRoute
  '/console/dashboard/del': typeof ConsoleDashboardDelRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/console': typeof ConsoleRouteWithChildren
  '/menu': typeof MenuRouteWithChildren
  '/console/dashboard': typeof ConsoleDashboardRouteWithChildren
  '/console/financa': typeof ConsoleFinancaRoute
  '/console/pedidos': typeof ConsolePedidosRoute
  '/menu/$categoryId': typeof MenuCategoryIdRoute
  '/console/dashboard/add': typeof ConsoleDashboardAddRoute
  '/console/dashboard/del': typeof ConsoleDashboardDelRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/console': typeof ConsoleRouteWithChildren
  '/menu': typeof MenuRouteWithChildren
  '/console/dashboard': typeof ConsoleDashboardRouteWithChildren
  '/console/financa': typeof ConsoleFinancaRoute
  '/console/pedidos': typeof ConsolePedidosRoute
  '/menu/$categoryId': typeof MenuCategoryIdRoute
  '/console/dashboard/add': typeof ConsoleDashboardAddRoute
  '/console/dashboard/del': typeof ConsoleDashboardDelRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/console'
    | '/menu'
    | '/console/dashboard'
    | '/console/financa'
    | '/console/pedidos'
    | '/menu/$categoryId'
    | '/console/dashboard/add'
    | '/console/dashboard/del'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/console'
    | '/menu'
    | '/console/dashboard'
    | '/console/financa'
    | '/console/pedidos'
    | '/menu/$categoryId'
    | '/console/dashboard/add'
    | '/console/dashboard/del'
  id:
    | '__root__'
    | '/'
    | '/console'
    | '/menu'
    | '/console/dashboard'
    | '/console/financa'
    | '/console/pedidos'
    | '/menu/$categoryId'
    | '/console/dashboard/add'
    | '/console/dashboard/del'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConsoleRoute: typeof ConsoleRouteWithChildren
  MenuRoute: typeof MenuRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu/$categoryId': {
      id: '/menu/$categoryId'
      path: '/$categoryId'
      fullPath: '/menu/$categoryId'
      preLoaderRoute: typeof MenuCategoryIdRouteImport
      parentRoute: typeof MenuRoute
    }
    '/console/pedidos': {
      id: '/console/pedidos'
      path: '/pedidos'
      fullPath: '/console/pedidos'
      preLoaderRoute: typeof ConsolePedidosRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/financa': {
      id: '/console/financa'
      path: '/financa'
      fullPath: '/console/financa'
      preLoaderRoute: typeof ConsoleFinancaRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/dashboard': {
      id: '/console/dashboard'
      path: '/dashboard'
      fullPath: '/console/dashboard'
      preLoaderRoute: typeof ConsoleDashboardRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/dashboard/del': {
      id: '/console/dashboard/del'
      path: '/del'
      fullPath: '/console/dashboard/del'
      preLoaderRoute: typeof ConsoleDashboardDelRouteImport
      parentRoute: typeof ConsoleDashboardRoute
    }
    '/console/dashboard/add': {
      id: '/console/dashboard/add'
      path: '/add'
      fullPath: '/console/dashboard/add'
      preLoaderRoute: typeof ConsoleDashboardAddRouteImport
      parentRoute: typeof ConsoleDashboardRoute
    }
  }
}

interface ConsoleDashboardRouteChildren {
  ConsoleDashboardAddRoute: typeof ConsoleDashboardAddRoute
  ConsoleDashboardDelRoute: typeof ConsoleDashboardDelRoute
}

const ConsoleDashboardRouteChildren: ConsoleDashboardRouteChildren = {
  ConsoleDashboardAddRoute: ConsoleDashboardAddRoute,
  ConsoleDashboardDelRoute: ConsoleDashboardDelRoute,
}

const ConsoleDashboardRouteWithChildren =
  ConsoleDashboardRoute._addFileChildren(ConsoleDashboardRouteChildren)

interface ConsoleRouteChildren {
  ConsoleDashboardRoute: typeof ConsoleDashboardRouteWithChildren
  ConsoleFinancaRoute: typeof ConsoleFinancaRoute
  ConsolePedidosRoute: typeof ConsolePedidosRoute
}

const ConsoleRouteChildren: ConsoleRouteChildren = {
  ConsoleDashboardRoute: ConsoleDashboardRouteWithChildren,
  ConsoleFinancaRoute: ConsoleFinancaRoute,
  ConsolePedidosRoute: ConsolePedidosRoute,
}

const ConsoleRouteWithChildren =
  ConsoleRoute._addFileChildren(ConsoleRouteChildren)

interface MenuRouteChildren {
  MenuCategoryIdRoute: typeof MenuCategoryIdRoute
}

const MenuRouteChildren: MenuRouteChildren = {
  MenuCategoryIdRoute: MenuCategoryIdRoute,
}

const MenuRouteWithChildren = MenuRoute._addFileChildren(MenuRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConsoleRoute: ConsoleRouteWithChildren,
  MenuRoute: MenuRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
